------------------------------------------------------------
-- ZYNTRA HE - ESTRUTURA DO BANCO (ORACLE)
-- Tabelas:
--  T_USUARIOS, T_TUTORES, T_CURSOS, T_OFICINAS, T_MENTORIAS
------------------------------------------------------------

------------------------------------------------------------
-- Tabela: T_USUARIOS
-- Armazena os usuários do sistema (login/acesso)
-- Regras:
--  PK: ID
--  UK: EMAIL
--  NN: EMAIL, SENHA, NOME
--  CK: tamanho mínimo da senha
------------------------------------------------------------
CREATE TABLE T_USUARIOS (
    ID               NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    EMAIL            VARCHAR2(255)    NOT NULL,
    SENHA            VARCHAR2(255)    NOT NULL,
    NOME             VARCHAR2(255)    NOT NULL,
    DATA_CRIACAO     TIMESTAMP        DEFAULT SYSTIMESTAMP,
    DATA_ATUALIZACAO TIMESTAMP        DEFAULT SYSTIMESTAMP,
    CONSTRAINT PK_T_USUARIOS PRIMARY KEY (ID),
    CONSTRAINT UK_T_USUARIOS_EMAIL UNIQUE (EMAIL),
    CONSTRAINT CK_T_USUARIOS_SENHA_MIN CHECK (LENGTH(SENHA) >= 6)
);

------------------------------------------------------------
-- Tabela: T_TUTORES
-- Armazena os tutores/mentores de negócios
-- Regras:
--  PK: ID
--  UK: EMAIL
--  NN: NOME, ESPECIALIDADE, EMAIL, TELEFONE
--  CK: tamanho mínimo de telefone, flag de ativo
------------------------------------------------------------
CREATE TABLE T_TUTORES (
    ID               NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    NOME             VARCHAR2(255)    NOT NULL,
    ESPECIALIDADE    VARCHAR2(255)    NOT NULL,
    EMAIL            VARCHAR2(255)    NOT NULL,
    TELEFONE         VARCHAR2(50)     NOT NULL,
    DATA_CRIACAO     TIMESTAMP        DEFAULT SYSTIMESTAMP,
    DATA_ATUALIZACAO TIMESTAMP        DEFAULT SYSTIMESTAMP,
    ATIVO            CHAR(1)          DEFAULT 'S',
    CONSTRAINT PK_T_TUTORES PRIMARY KEY (ID),
    CONSTRAINT UK_T_TUTORES_EMAIL UNIQUE (EMAIL),
    CONSTRAINT CK_T_TUTORES_TELEFONE_LEN CHECK (LENGTH(TELEFONE) >= 10),
    CONSTRAINT CK_T_TUTORES_ATIVO CHECK (ATIVO IN ('S','N'))
);

------------------------------------------------------------
-- Tabela: T_CURSOS
-- Catálogo de cursos oferecidos aos empreendedores
-- Regras:
--  PK: ID
--  NN: TITULO
--  CK: ATIVO (S/N), URL iniciando com HTTP
------------------------------------------------------------
CREATE TABLE T_CURSOS (
    ID               NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    TITULO           VARCHAR2(255)    NOT NULL,
    DESCRICAO        CLOB,
    DURACAO          VARCHAR2(100),
    FORMATO          VARCHAR2(100),
    PRECO            VARCHAR2(50),
    URL              VARCHAR2(500),
    DATA_CRIACAO     TIMESTAMP        DEFAULT SYSTIMESTAMP,
    DATA_ATUALIZACAO TIMESTAMP        DEFAULT SYSTIMESTAMP,
    ATIVO            CHAR(1)          DEFAULT 'S',
    CONSTRAINT PK_T_CURSOS PRIMARY KEY (ID),
    CONSTRAINT CK_T_CURSOS_ATIVO CHECK (ATIVO IN ('S','N')),
    CONSTRAINT CK_T_CURSOS_URL CHECK (URL IS NULL OR URL LIKE 'HTTP%')
);

------------------------------------------------------------
-- Tabela: T_OFICINAS
-- Oficinas/empreendimentos cadastrados na plataforma
-- Regras:
--  PK: ID
--  UK: CNPJ
--  NN: NOME_EMPREENDIMENTO, CNPJ, NOME_EMPRESA, LOCALIZACAO, SERVICOS
--  CK: CNPJ com 14 caracteres, ESTADO com 2, STATUS válido, AVALIACAO 0..5
------------------------------------------------------------
CREATE TABLE T_OFICINAS (
    ID                  NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    NOME_EMPREENDIMENTO VARCHAR2(255)    NOT NULL,
    CNPJ                VARCHAR2(14)     NOT NULL,
    NOME_EMPRESA        VARCHAR2(255)    NOT NULL,
    LOCALIZACAO         CLOB             NOT NULL,
    SERVICOS            CLOB             NOT NULL,
    CIDADE              VARCHAR2(100),
    ESTADO              VARCHAR2(2),
    ESPECIALIDADE       VARCHAR2(255),
    AVALIACAO           NUMBER(3,2)      DEFAULT 0,
    DATA_CRIACAO        TIMESTAMP        DEFAULT SYSTIMESTAMP,
    DATA_ATUALIZACAO    TIMESTAMP        DEFAULT SYSTIMESTAMP,
    STATUS              VARCHAR2(20)     DEFAULT 'PENDENTE',
    CONSTRAINT PK_T_OFICINAS PRIMARY KEY (ID),
    CONSTRAINT UK_T_OFICINAS_CNPJ UNIQUE (CNPJ),
    CONSTRAINT CK_T_OFICINAS_CNPJ_LEN CHECK (LENGTH(CNPJ) = 14),
    CONSTRAINT CK_T_OFICINAS_ESTADO CHECK (ESTADO IS NULL OR LENGTH(ESTADO) = 2),
    CONSTRAINT CK_T_OFICINAS_STATUS CHECK (STATUS IN ('PENDENTE','APROVADA','REJEITADA','INATIVA')),
    CONSTRAINT CK_T_OFICINAS_AVALIACAO CHECK (AVALIACAO BETWEEN 0 AND 5)
);

------------------------------------------------------------
-- Tabela: T_MENTORIAS
-- Agendamentos de mentorias entre usuários e tutores
-- Regras:
--  PK: ID
--  FK: TUTOR_ID -> T_TUTORES, USUARIO_ID -> T_USUARIOS
--  NN: NOME_COMPLETO, CPF, EMAIL, TELEFONE, DATA
--  CK: CPF com 11 caracteres, STATUS válido
------------------------------------------------------------
CREATE TABLE T_MENTORIAS (
    ID               NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    NOME_COMPLETO    VARCHAR2(255)    NOT NULL,
    CPF              VARCHAR2(11)     NOT NULL,
    EMAIL            VARCHAR2(255)    NOT NULL,
    TELEFONE         VARCHAR2(50)     NOT NULL,
    DATA             DATE             NOT NULL,
    DATA_CRIACAO     TIMESTAMP        DEFAULT SYSTIMESTAMP,
    STATUS           VARCHAR2(20)     DEFAULT 'AGENDADA',
    TUTOR_ID         NUMBER(19),
    USUARIO_ID       NUMBER(19),
    CONSTRAINT PK_T_MENTORIAS PRIMARY KEY (ID),
    CONSTRAINT CK_T_MENTORIAS_CPF_LEN CHECK (LENGTH(CPF) = 11),
    CONSTRAINT CK_T_MENTORIAS_STATUS CHECK (STATUS IN ('AGENDADA','CONFIRMADA','CANCELADA','REALIZADA')),
    CONSTRAINT FK_T_MENTORIAS_TUTOR FOREIGN KEY (TUTOR_ID)
        REFERENCES T_TUTORES (ID),
    CONSTRAINT FK_T_MENTORIAS_USUARIO FOREIGN KEY (USUARIO_ID)
        REFERENCES T_USUARIOS (ID)
);

------------------------------------------------------------
-- Comentários (opcionais, mas deixam o modelo mais descritivo)
------------------------------------------------------------
COMMENT ON TABLE T_USUARIOS  IS 'Usuários da plataforma Zyntra HE';
COMMENT ON TABLE T_TUTORES   IS 'Tutores/mentores disponíveis para mentorias';
COMMENT ON TABLE T_CURSOS    IS 'Cursos oferecidos para capacitação dos empreendedores';
COMMENT ON TABLE T_OFICINAS  IS 'Oficinas e empreendimentos cadastrados';
COMMENT ON TABLE T_MENTORIAS IS 'Agendamentos de mentorias entre usuários e tutores';

------------------------------------------------------------
-- DROP DAS TABELAS (UTILIZAR NESTA ORDEM POR CAUSA DAS FKs)
------------------------------------------------------------

-- Primeiro, tabelas que possuem chaves estrangeiras para outras
DROP TABLE T_MENTORIAS CASCADE CONSTRAINTS;

-- Demais tabelas independentes
DROP TABLE T_OFICINAS CASCADE CONSTRAINTS;
DROP TABLE T_CURSOS   CASCADE CONSTRAINTS;
DROP TABLE T_TUTORES  CASCADE CONSTRAINTS;
DROP TABLE T_USUARIOS CASCADE CONSTRAINTS;



