------------------------------------------------------------
-- ZYNTRA HE - ESTRUTURA DO BANCO (ORACLE)
-- Tabelas:
--  T_ZYNT_USUARIOS, T_ZYNT_TUTORES, T_ZYNT_CURSOS, T_ZYNT_OFICINAS, T_ZYNT_MENTORIAS, 
--  T_ZYNT_AULAS_CURSO, T_ZYNT_PONTOS_RECARGA, T_ZYNT_OFICINA_SERVICOS
------------------------------------------------------------

------------------------------------------------------------
-- Tabela: T_ZYNT_USUARIOS
-- Armazena os usuários do sistema (login/acesso)
-- Regras:
--  PK: ID
--  UK: EMAIL
--  NN: EMAIL, SENHA, NOME
--  CK: tamanho mínimo da senha
------------------------------------------------------------
CREATE TABLE T_ZYNT_USUARIOS (
    ID               NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    EMAIL            VARCHAR2(255)    NOT NULL,
    SENHA            VARCHAR2(255)    NOT NULL,
    NOME             VARCHAR2(255)    NOT NULL,
    DATA_CRIACAO     TIMESTAMP        DEFAULT SYSTIMESTAMP,
    DATA_ATUALIZACAO TIMESTAMP        DEFAULT SYSTIMESTAMP,
    CONSTRAINT PK_T_ZYNT_USUARIOS PRIMARY KEY (ID),
    CONSTRAINT UK_T_ZYNT_USUARIOS_EMAIL UNIQUE (EMAIL),
    CONSTRAINT CK_T_ZYNT_USUARIOS_SENHA_MIN CHECK (LENGTH(SENHA) >= 6)
);

------------------------------------------------------------
-- Tabela: T_ZYNT_TUTORES
-- Armazena os tutores/mentores de negócios
-- Regras:
--  PK: ID
--  UK: EMAIL
--  NN: NOME, ESPECIALIDADE, EMAIL, TELEFONE
--  CK: tamanho mínimo de telefone, flag de ativo
------------------------------------------------------------
CREATE TABLE T_ZYNT_TUTORES (
    ID               NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    NOME             VARCHAR2(255)    NOT NULL,
    ESPECIALIDADE    VARCHAR2(255)    NOT NULL,
    EMAIL            VARCHAR2(255)    NOT NULL,
    TELEFONE         VARCHAR2(50)     NOT NULL,
    DATA_CRIACAO     TIMESTAMP        DEFAULT SYSTIMESTAMP,
    DATA_ATUALIZACAO TIMESTAMP        DEFAULT SYSTIMESTAMP,
    ATIVO            CHAR(1)          DEFAULT 'S',
    CONSTRAINT PK_T_ZYNT_TUTORES PRIMARY KEY (ID),
    CONSTRAINT UK_T_ZYNT_TUTORES_EMAIL UNIQUE (EMAIL),
    CONSTRAINT CK_T_ZYNT_TUTORES_TELEFONE_LEN CHECK (LENGTH(TELEFONE) >= 10),
    CONSTRAINT CK_T_ZYNT_TUTORES_ATIVO CHECK (ATIVO IN ('S','N'))
);

------------------------------------------------------------
-- Tabela: T_ZYNT_CURSOS
-- Catálogo de cursos oferecidos aos empreendedores
-- Regras:
--  PK: ID
--  NN: TITULO
--  CK: ATIVO (S/N)
------------------------------------------------------------
CREATE TABLE T_ZYNT_CURSOS (
    ID               NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    TITULO           VARCHAR2(255)    NOT NULL,
    DESCRICAO        CLOB,
    DATA_CRIACAO     TIMESTAMP        DEFAULT SYSTIMESTAMP,
    DATA_ATUALIZACAO TIMESTAMP        DEFAULT SYSTIMESTAMP,
    ATIVO            CHAR(1)          DEFAULT 'S',
    CONSTRAINT PK_T_ZYNT_CURSOS PRIMARY KEY (ID),
    CONSTRAINT CK_T_ZYNT_CURSOS_ATIVO CHECK (ATIVO IN ('S','N'))
);

------------------------------------------------------------
-- Tabela: T_ZYNT_OFICINAS
-- Oficinas/empreendimentos cadastrados na plataforma
-- Regras:
--  PK: ID
--  UK: CNPJ
--  NN: NOME_EMPREENDIMENTO, CNPJ, NOME_EMPRESA, LOCALIZACAO
--  CK: CNPJ com 14 caracteres, ESTADO com 2, STATUS válido, AVALIACAO 0..5
------------------------------------------------------------
CREATE TABLE T_ZYNT_OFICINAS (
    ID                  NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    NOME_EMPREENDIMENTO VARCHAR2(255)    NOT NULL,
    CNPJ                VARCHAR2(14)     NOT NULL,
    NOME_EMPRESA        VARCHAR2(255)    NOT NULL,
    LOCALIZACAO         CLOB             NOT NULL,
    CIDADE              VARCHAR2(100),
    ESTADO              VARCHAR2(2),
    ESPECIALIDADE       VARCHAR2(255),
    AVALIACAO           NUMBER(3,2)      DEFAULT 0,
    DATA_CRIACAO        TIMESTAMP        DEFAULT SYSTIMESTAMP,
    DATA_ATUALIZACAO    TIMESTAMP        DEFAULT SYSTIMESTAMP,
    STATUS              VARCHAR2(20)     DEFAULT 'PENDENTE',
    CONSTRAINT PK_T_ZYNT_OFICINAS PRIMARY KEY (ID),
    CONSTRAINT UK_T_ZYNT_OFICINAS_CNPJ UNIQUE (CNPJ),
    CONSTRAINT CK_T_ZYNT_OFICINAS_CNPJ_LEN CHECK (LENGTH(CNPJ) = 14),
    CONSTRAINT CK_T_ZYNT_OFICINAS_ESTADO CHECK (ESTADO IS NULL OR LENGTH(ESTADO) = 2),
    CONSTRAINT CK_T_ZYNT_OFICINAS_STATUS CHECK (STATUS IN ('PENDENTE','APROVADA','REJEITADA','INATIVA')),
    CONSTRAINT CK_T_ZYNT_OFICINAS_AVALIACAO CHECK (AVALIACAO BETWEEN 0 AND 5)
);

------------------------------------------------------------
-- Tabela: T_ZYNT_OFICINA_SERVICOS
-- Serviços oferecidos pelas oficinas
-- Uma oficina pode oferecer múltiplos serviços
-- Regras:
--  PK: ID
--  FK: OFICINA_ID -> T_ZYNT_OFICINAS
--  NN: OFICINA_ID, NOME
--  CK: ATIVO (S/N)
------------------------------------------------------------
CREATE TABLE T_ZYNT_OFICINA_SERVICOS (
    ID                  NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    OFICINA_ID          NUMBER(19)       NOT NULL,
    NOME                VARCHAR2(255)    NOT NULL,
    DESCRICAO           CLOB,
    ATIVO               CHAR(1)          DEFAULT 'S',
    DATA_CRIACAO        TIMESTAMP        DEFAULT SYSTIMESTAMP,
    DATA_ATUALIZACAO    TIMESTAMP        DEFAULT SYSTIMESTAMP,
    CONSTRAINT PK_T_ZYNT_OFICINA_SERVICOS PRIMARY KEY (ID),
    CONSTRAINT FK_T_ZYNT_OFICINA_SERVICOS_OFICINA FOREIGN KEY (OFICINA_ID)
        REFERENCES T_ZYNT_OFICINAS (ID) ON DELETE CASCADE,
    CONSTRAINT CK_T_ZYNT_OFICINA_SERVICOS_ATIVO CHECK (ATIVO IN ('S','N'))
);

------------------------------------------------------------
-- Tabela: T_ZYNT_MENTORIAS
-- Agendamentos de mentorias entre usuários e tutores
-- Regras:
--  PK: ID
--  FK: TUTOR_ID -> T_ZYNT_TUTORES, USUARIO_ID -> T_ZYNT_USUARIOS
--  NN: NOME_COMPLETO, CPF, EMAIL, TELEFONE, DATA
--  CK: CPF com 11 caracteres, STATUS válido
------------------------------------------------------------
CREATE TABLE T_ZYNT_MENTORIAS (
    ID               NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    NOME_COMPLETO    VARCHAR2(255)    NOT NULL,
    CPF              VARCHAR2(11)     NOT NULL,
    EMAIL            VARCHAR2(255)    NOT NULL,
    TELEFONE         VARCHAR2(50)     NOT NULL,
    DATA             DATE             NOT NULL,
    DATA_CRIACAO     TIMESTAMP        DEFAULT SYSTIMESTAMP,
    STATUS           VARCHAR2(20)     DEFAULT 'AGENDADA',
    TUTOR_ID         NUMBER(19),
    USUARIO_ID       NUMBER(19),
    CONSTRAINT PK_T_ZYNT_MENTORIAS PRIMARY KEY (ID),
    CONSTRAINT CK_T_ZYNT_MENTORIAS_CPF_LEN CHECK (LENGTH(CPF) = 11),
    CONSTRAINT CK_T_ZYNT_MENTORIAS_STATUS CHECK (STATUS IN ('AGENDADA','CONFIRMADA','CANCELADA','REALIZADA')),
    CONSTRAINT FK_T_ZYNT_MENTORIAS_TUTOR FOREIGN KEY (TUTOR_ID)
        REFERENCES T_ZYNT_TUTORES (ID),
    CONSTRAINT FK_T_ZYNT_MENTORIAS_USUARIO FOREIGN KEY (USUARIO_ID)
        REFERENCES T_ZYNT_USUARIOS (ID)
);

------------------------------------------------------------
-- Tabela: T_ZYNT_AULAS_CURSO
-- Aulas que compõem os cursos oferecidos
-- Regras:
--  PK: ID
--  FK: CURSO_ID -> T_ZYNT_CURSOS
--  NN: TITULO, CURSO_ID
--  CK: ATIVO (S/N), URL iniciando com HTTP/HTTPS (case-insensitive)
------------------------------------------------------------
CREATE TABLE T_ZYNT_AULAS_CURSO (
    ID                  NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    CURSO_ID            NUMBER(19)         NOT NULL,
    TITULO              VARCHAR2(255)      NOT NULL,
    DESCRICAO           CLOB,
    URL                 VARCHAR2(500),
    ATIVO               CHAR(1)            DEFAULT 'S',
    DATA_CRIACAO        TIMESTAMP         DEFAULT SYSTIMESTAMP,
    DATA_ATUALIZACAO    TIMESTAMP         DEFAULT SYSTIMESTAMP,
    CONSTRAINT PK_T_ZYNT_AULAS_CURSO PRIMARY KEY (ID),
    CONSTRAINT FK_T_ZYNT_AULAS_CURSO_CURSO FOREIGN KEY (CURSO_ID)
        REFERENCES T_ZYNT_CURSOS (ID) ON DELETE CASCADE,
    CONSTRAINT CK_T_ZYNT_AULAS_CURSO_ATIVO CHECK (ATIVO IN ('S','N')),
    CONSTRAINT CK_T_ZYNT_AULAS_CURSO_URL CHECK (URL IS NULL OR UPPER(URL) LIKE 'HTTP%')
);

------------------------------------------------------------
-- Tabela: T_ZYNT_PONTOS_RECARGA
-- Pontos de recarga para veículos elétricos e híbridos
-- Regras:
--  PK: ID
--  NN: NOME, ENDERECO, TIPO_RECARGA
--  CK: TIPO_RECARGA válido
------------------------------------------------------------
CREATE TABLE T_ZYNT_PONTOS_RECARGA (
    ID                  NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    NOME                VARCHAR2(255)      NOT NULL,
    ENDERECO            VARCHAR2(500)      NOT NULL,
    TIPO_RECARGA        VARCHAR2(50)       DEFAULT 'AC',
    DATA_CRIACAO        TIMESTAMP         DEFAULT SYSTIMESTAMP,
    DATA_ATUALIZACAO    TIMESTAMP         DEFAULT SYSTIMESTAMP,
    CONSTRAINT PK_T_ZYNT_PONTOS_RECARGA PRIMARY KEY (ID),
    CONSTRAINT CK_T_ZYNT_PONTOS_RECARGA_TIPO CHECK (TIPO_RECARGA IN ('AC','DC','AC_DC'))
);

------------------------------------------------------------
-- Comentários (opcionais, mas deixam o modelo mais descritivo)
------------------------------------------------------------
COMMENT ON TABLE T_ZYNT_USUARIOS  IS 'Usuários da plataforma Zyntra HE';
COMMENT ON TABLE T_ZYNT_TUTORES   IS 'Tutores/mentores disponíveis para mentorias';
COMMENT ON TABLE T_ZYNT_CURSOS    IS 'Cursos oferecidos para capacitação dos empreendedores';
COMMENT ON TABLE T_ZYNT_OFICINAS  IS 'Oficinas e empreendimentos cadastrados';
COMMENT ON TABLE T_ZYNT_MENTORIAS IS 'Agendamentos de mentorias entre usuários e tutores';
COMMENT ON TABLE T_ZYNT_AULAS_CURSO IS 'Aulas que compõem os cursos oferecidos';
COMMENT ON TABLE T_ZYNT_PONTOS_RECARGA IS 'Pontos de recarga para veículos elétricos e híbridos';
COMMENT ON TABLE T_ZYNT_OFICINA_SERVICOS IS 'Serviços oferecidos pelas oficinas';

------------------------------------------------------------
-- DROP DAS TABELAS (UTILIZAR NESTA ORDEM POR CAUSA DAS FKs)
------------------------------------------------------------

-- Primeiro, tabelas que possuem chaves estrangeiras para outras
DROP TABLE T_ZYNT_OFICINA_SERVICOS CASCADE CONSTRAINTS;
DROP TABLE T_ZYNT_AULAS_CURSO CASCADE CONSTRAINTS;
DROP TABLE T_ZYNT_MENTORIAS CASCADE CONSTRAINTS;

-- Demais tabelas independentes
DROP TABLE T_ZYNT_PONTOS_RECARGA CASCADE CONSTRAINTS;
DROP TABLE T_ZYNT_OFICINAS CASCADE CONSTRAINTS;
DROP TABLE T_ZYNT_CURSOS   CASCADE CONSTRAINTS;
DROP TABLE T_ZYNT_TUTORES  CASCADE CONSTRAINTS;
DROP TABLE T_ZYNT_USUARIOS CASCADE CONSTRAINTS;
